{{ if .Values.ingress.enabled -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.global.project }}-{{ .Values.global.environmentShort }}-cert
spec:
  secretName: {{ .Values.global.project }}-{{ .Values.global.environmentShort }}-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "{{ .Values.global.project }}-{{ .Values.global.environmentShort }}.{{ .Values.global.topLevelDomain }}"
  acme:
    config:
    - dns01:
        provider: azure
      domains:
      - "{{ .Values.global.project }}-{{ .Values.global.environmentShort }}.{{ .Values.global.topLevelDomain }}"
{{ end }}