apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  labels:
    app: {{ .Values.application.name }}
spec:
  ports:
  - port: {{ .Values.application.port }}
    targetPort: {{ .Values.application.port }}
    name: http
    protocol: TCP
  selector:
    app: {{ .Values.application.name }}